plugins:
  discourse_tag_intersection_navigator_enabled:
    default: true
  discourse_tag_intersection_navigator_all_word:
    default: "everything"
    client: true
  discourse_tag_intersection_navigator_make_intersection_homepage:
    default: false
    client: true
  discourse_tag_intersection_navigator_add_community_link:
    default: true
    client: true